parameters:
    app.oauth_user_provider.class: Fuz\AppBundle\Model\OAuthUserProvider
    hwi_oauth.account.connector: Fuz\AppBundle\Connect\AccountConnect
    app.form.fiddle.class: Fuz\AppBundle\Form\FiddleType
    app.twig.debug_extension.class: Fuz\AppBundle\Twig\Extension\DebugExtension
    app.twig.safety_extension.class: Fuz\AppBundle\Twig\Extension\SafetyExtension
    app.twig.github_extension.class: Fuz\AppBundle\Twig\Extension\GitHubExtension
    app.twig.hash_extension.class: Fuz\AppBundle\Twig\Extension\HashExtension
    app.twig.pcre_extension.class: Fuz\AppBundle\Twig\Extension\PcreExtension
    app.helper.doctrine_helper.class: Fuz\AppBundle\Helper\DoctrineHelper
    app.subscriber.fiddle.class: Fuz\AppBundle\EventListener\FiddleSubscriber
    app.subscriber.user.class: Fuz\AppBundle\EventListener\UserSubscriber
    app.subscriber.user_bookmark.class: Fuz\AppBundle\EventListener\UserBookmarkSubscriber
    app.utilities.class: Fuz\AppBundle\Service\Utilities
    app.paginator.class: Fuz\AppBundle\Service\Paginator
    app.process_configuration.class: Fuz\AppBundle\Service\ProcessConfiguration
    app.run_fiddle.class: Fuz\AppBundle\Service\RunFiddle
    app.save_fiddle.class: Fuz\AppBundle\Service\SaveFiddle
    app.search_fiddle.class: Fuz\AppBundle\Service\SearchFiddle

services:

    app.oauth_user_provider:
        class: %app.oauth_user_provider.class%
        arguments: [@session, @doctrine.orm.entity_manager]

    hwi_oauth.account.connector:
        class: %hwi_oauth.account.connector%

    app.form.fiddle:
         class: %app.form.fiddle.class%
         arguments: [@app.process_configuration]
         tags:
            - { name: form.type, alias: FiddleType }

    app.twig.debug_extension:
         class: %app.twig.debug_extension.class%
         arguments: []
         tags:
             - { name: twig.extension }

    app.twig.safety_extension:
         class: %app.twig.safety_extension.class%
         arguments: [%kernel.root_dir%]
         tags:
             - { name: twig.extension }

    app.twig.github_extension:
         class: %app.twig.github_extension.class%
         arguments: [%github_repository_root%]
         tags:
             - { name: twig.extension }

    app.twig.hash_extension:
         class: %app.twig.hash_extension.class%
         arguments: []
         tags:
             - { name: twig.extension }

    app.twig.pcre_extension:
         class: %app.twig.pcre_extension.class%
         arguments: []
         tags:
             - { name: twig.extension }

    app.helper.doctrine_helper:
         class: %app.helper.doctrine_helper.class%
         arguments: [@doctrine.orm.entity_manager]

    app.subscriber.fiddle:
        class: %app.subscriber.fiddle.class%
        tags:
             - { name: doctrine.event_subscriber, connection: default }

    app.subscriber.user:
        class: %app.subscriber.user.class%
        tags:
             - { name: doctrine.event_subscriber, connection: default }

    app.subscriber.user_bookmark:
        class: %app.subscriber.user_bookmark.class%
        tags:
             - { name: doctrine.event_subscriber, connection: default }

    app.utilities:
         class: %app.utilities.class%
         arguments: [@logger]
         tags:
             - { name: monolog.logger, channel: service.utilities }

    app.paginator:
         class: %app.paginator.class%
         arguments: [@logger, @session, @security.token_storage]
         tags:
             - { name: monolog.logger, channel: service.paginator }

    app.process_configuration:
        class: %app.process_configuration.class%
        arguments: [@logger, %process%, %kernel.environment%]
        tags:
            - { name: monolog.logger, channel: service.process_configuration }

    app.run_fiddle:
         class: %app.run_fiddle.class%
         arguments: [@logger, @filesystem, @app.utilities, @app.process_configuration, %process%]
         tags:
             - { name: monolog.logger, channel: service.run_fiddle }

    app.save_fiddle:
         class: %app.save_fiddle.class%
         arguments: [@logger, @app.utilities, @app.helper.doctrine_helper, @doctrine.orm.entity_manager, @session, @router, %web%]
         tags:
             - { name: monolog.logger, channel: service.save_fiddle }

    app.search_fiddle:
         class: %app.search_fiddle.class%
         arguments: [@logger, @doctrine.orm.entity_manager, @app.paginator, %web%]
         tags:
             - { name: monolog.logger, channel: service.search_fiddle }
