parameters:
    v1.twig_engine.class: 'Fuz\Process\TwigEngine\V1TwigEngine'
    v2.twig_engine.class: 'Fuz\Process\TwigEngine\V2TwigEngine'

services:

    v2.twig_engine:
        class: '%v2.twig_engine.class%'
        arguments: ['@fiddle_agent']
        tags:
            -
                name: twig.engine
                versions: 'Twig-2.2.0 / Twig-2.1.0 / Twig-2.0.0'
                label: Twig 2.x

    v1.twig_engine:
        class: '%v2.twig_engine.class%'
        arguments: ['@fiddle_agent']
        tags:
            -
                name: twig.engine
                versions: 'Twig-1.32.0 / Twig-1.31.0 / Twig-1.30.0 / Twig-1.29.0 / Twig-1.28.2 / Twig-1.28.1 / Twig-1.28.0 / Twig-1.27.0 / Twig-1.26.1 / Twig-1.26.0 / Twig-1.25.0 / Twig-1.24.2 / Twig-1.24.1 / Twig-1.24.0 / Twig-1.23.3 / Twig-1.23.2 / Twig-1.23.1 / Twig-1.23.0 / Twig-1.22.3 / Twig-1.22.2 / Twig-1.22.1 / Twig-1.22.0 / Twig-1.21.2 / Twig-1.21.1 / Twig-1.21.0 / Twig-1.20.0 / Twig-1.19.0 / Twig-1.18.2 / Twig-1.18.1 / Twig-1.18.0 / Twig-1.17.0 / Twig-1.16.3 / Twig-1.16.2 / Twig-1.16.1 / Twig-1.16.0 / Twig-1.15.1 / Twig-1.15.0 / Twig-1.14.2 / Twig-1.14.1 / Twig-1.14.0 / Twig-1.13.2 / Twig-1.13.1 / Twig-1.13.0 / Twig-1.12.3 / Twig-1.12.2 / Twig-1.12.1 / Twig-1.12.0 / Twig-1.12.0-RC1 / Twig-1.11.1 / Twig-1.11.0 / Twig-1.10.3 / Twig-1.10.2 / Twig-1.10.1 / Twig-1.10.0 / Twig-1.9.2 / Twig-1.9.1 / Twig-1.9.0 / Twig-1.8.3 / Twig-1.8.2 / Twig-1.8.1 / Twig-1.8.0 / Twig-1.7.0 / Twig-1.6.5 / Twig-1.6.4 / Twig-1.6.3 / Twig-1.6.2 / Twig-1.6.1 / Twig-1.6.0 / Twig-1.5.1 / Twig-1.5.0 / Twig-1.5.0-RC2 / Twig-1.5.0-RC1 / Twig-1.4.0 / Twig-1.4.0-RC2 / Twig-1.4.0-RC1 / Twig-1.3.0 / Twig-1.3.0-RC1 / Twig-1.2.0 / Twig-1.2.0-RC1 / Twig-1.1.2 / Twig-1.1.1 / Twig-1.1.0 / Twig-1.1.0-RC3 / Twig-1.1.0-RC2 / Twig-1.1.0-RC1 / Twig-1.0.0 / Twig-1.0.0-RC2 / Twig-1.0.0-RC1'
                label: Twig 1.x

    v0.twig_engine:
        class: '%v1.twig_engine.class%'
        arguments: ['@fiddle_agent']
        tags:
            -
                name: twig.engine
                versions: 'Twig-0.9.10 / Twig-0.9.9 / Twig-0.9.8 / Twig-0.9.7 / Twig-0.9.6 / Twig-0.9.5 / Twig-0.9.4 / Twig-0.9.2 / Twig-0.9.1 / Twig-0.9.0'
                label: Twig 0.x
