parameters:
    default.twig_engine.class: Fuz\Process\TwigEngine\DefaultTwigEngine

services:

    default.twig_engine:
        class: %default.twig_engine.class%
        arguments: []
        tags:
         - { name: twig.engine, versions: Twig-1.17.0 / Twig-1.16.3 / Twig-1.16.2 / Twig-1.16.1 / Twig-1.16.0 / Twig-1.15.1 / Twig-1.15.0 / Twig-1.14.2 / Twig-1.14.1 / Twig-1.14.0 / Twig-1.13.2 / Twig-1.13.1 / Twig-1.13.0 / Twig-1.12.3 / Twig-1.12.2 / Twig-1.12.1 / Twig-1.12.0-RC1 / Twig-1.12.0 / Twig-1.11.1 / Twig-1.11.0 / Twig-1.10.3 / Twig-1.10.2 / Twig-1.10.1 / Twig-1.10.0 / Twig-1.9.2 / Twig-1.9.1 / Twig-1.9.0 / Twig-1.8.3 / Twig-1.8.2 / Twig-1.8.1 / Twig-1.8.0 / Twig-1.7.0 / Twig-1.6.5 / Twig-1.6.4 / Twig-1.6.3 / Twig-1.6.2 / Twig-1.6.1 / Twig-1.6.0 / Twig-1.5.1 / Twig-1.5.0-RC2 / Twig-1.5.0-RC1 / Twig-1.5.0 / Twig-1.4.0-RC2 / Twig-1.4.0-RC1 / Twig-1.4.0 / Twig-1.3.0-RC1 / Twig-1.3.0 / Twig-1.2.0-RC1 / Twig-1.2.0 / Twig-1.1.2 / Twig-1.1.1 / Twig-1.1.0-RC3 / Twig-1.1.0-RC2 / Twig-1.1.0-RC1 / Twig-1.1.0 / Twig-1.0.0-RC2 / Twig-1.0.0-RC1 / Twig-1.0.0 / Twig-0.9.10 / Twig-0.9.9 / Twig-0.9.8 / Twig-0.9.7 / Twig-0.9.6 / Twig-0.9.5 / Twig-0.9.4 / Twig-0.9.2 / Twig-0.9.1 / Twig-0.9.0 }
