parameters:
    twig_engine.class: Fuz\Process\TwigEngine\TwigEngine
services:
    v3.twig_engine:
        tags:
            -
                name: twig.engine
                versions: 'Twig-3.3.6 / Twig-3.3.5 / Twig-3.3.4 / Twig-3.3.3 / Twig-3.3.2 / Twig-3.3.1 / Twig-3.3.0 / Twig-3.2.1 / Twig-3.2.0 / Twig-3.1.1 / Twig-3.1.0 / Twig-3.0.5 / Twig-3.0.4 / Twig-3.0.3 / Twig-3.0.2 / Twig-3.0.1 / Twig-3.0.0 / Twig-3.0.0-BETA1'
                label: 'Twig 3.x'
    v2.twig_engine:
        class: '%twig_engine.class%'
        tags:
            -
                name: twig.engine
                versions: 'Twig-2.14.9 / Twig-2.14.8 / Twig-2.14.7 / Twig-2.14.6 / Twig-2.14.5 / Twig-2.14.4 / Twig-2.14.3 / Twig-2.14.2 / Twig-2.14.1 / Twig-2.14.0 / Twig-2.13.1 / Twig-2.13.0 / Twig-2.12.5 / Twig-2.12.4 / Twig-2.12.3 / Twig-2.12.2 / Twig-2.12.1 / Twig-2.12.0 / Twig-2.11.3 / Twig-2.11.2 / Twig-2.11.1 / Twig-2.11.0 / Twig-2.10.0 / Twig-2.9.0 / Twig-2.8.1 / Twig-2.8.0 / Twig-2.7.4 / Twig-2.7.3 / Twig-2.7.2 / Twig-2.7.1 / Twig-2.7.0 / Twig-2.6.2 / Twig-2.6.1 / Twig-2.6.0 / Twig-2.5.0 / Twig-2.4.8 / Twig-2.4.7 / Twig-2.4.6 / Twig-2.4.5 / Twig-2.4.4 / Twig-2.4.3 / Twig-2.4.2 / Twig-2.4.1 / Twig-2.4.0 / Twig-2.3.2 / Twig-2.3.1 / Twig-2.3.0 / Twig-2.2.0 / Twig-2.1.0 / Twig-2.0.0'
                label: 'Twig 2.x'
    v1.twig_engine:
        class: '%twig_engine.class%'
        tags:
            -
                name: twig.engine
                versions: 'Twig-1.42.0 / Twig-1.41.0 / Twig-1.40.1 / Twig-1.40.0 / Twig-1.39.1 / Twig-1.39.0 / Twig-1.38.4 / Twig-1.38.3 / Twig-1.38.2 / Twig-1.38.1 / Twig-1.38.0 / Twig-1.37.1 / Twig-1.37.0 / Twig-1.36.0 / Twig-1.35.4 / Twig-1.35.3 / Twig-1.35.2 / Twig-1.35.1 / Twig-1.35.0 / Twig-1.34.4 / Twig-1.34.3 / Twig-1.34.2 / Twig-1.34.1 / Twig-1.34.0 / Twig-1.33.2 / Twig-1.33.1 / Twig-1.33.0 / Twig-1.32.0 / Twig-1.31.0 / Twig-1.30.0 / Twig-1.29.0 / Twig-1.28.2 / Twig-1.28.1 / Twig-1.28.0 / Twig-1.27.0 / Twig-1.26.1 / Twig-1.26.0 / Twig-1.25.0 / Twig-1.24.2 / Twig-1.24.1 / Twig-1.24.0 / Twig-1.23.3 / Twig-1.23.2 / Twig-1.23.1 / Twig-1.23.0 / Twig-1.22.3 / Twig-1.22.2 / Twig-1.22.1 / Twig-1.22.0 / Twig-1.21.2 / Twig-1.21.1 / Twig-1.21.0 / Twig-1.20.0 / Twig-1.19.0 / Twig-1.18.2 / Twig-1.18.1 / Twig-1.18.0 / Twig-1.17.0 / Twig-1.16.3 / Twig-1.16.2 / Twig-1.16.1 / Twig-1.16.0 / Twig-1.15.1 / Twig-1.15.0 / Twig-1.14.2 / Twig-1.14.1 / Twig-1.14.0 / Twig-1.13.2 / Twig-1.13.1 / Twig-1.13.0 / Twig-1.12.3 / Twig-1.12.2 / Twig-1.12.1 / Twig-1.12.0 / Twig-1.12.0-RC1 / Twig-1.11.1 / Twig-1.11.0 / Twig-1.10.3 / Twig-1.10.2 / Twig-1.10.1 / Twig-1.10.0 / Twig-1.9.2 / Twig-1.9.1 / Twig-1.9.0 / Twig-1.8.3 / Twig-1.8.2 / Twig-1.8.1 / Twig-1.8.0 / Twig-1.7.0 / Twig-1.6.5 / Twig-1.6.4 / Twig-1.6.3 / Twig-1.6.2 / Twig-1.6.1 / Twig-1.6.0 / Twig-1.5.1 / Twig-1.5.0 / Twig-1.5.0-RC2 / Twig-1.5.0-RC1 / Twig-1.4.0 / Twig-1.4.0-RC2 / Twig-1.4.0-RC1 / Twig-1.3.0 / Twig-1.3.0-RC1 / Twig-1.2.0 / Twig-1.2.0-RC1 / Twig-1.1.2 / Twig-1.1.1 / Twig-1.1.0 / Twig-1.1.0-RC3 / Twig-1.1.0-RC2 / Twig-1.1.0-RC1 / Twig-1.0.0 / Twig-1.0.0-RC2 / Twig-1.0.0-RC1'
                label: 'Twig 1.x'
    v0.twig_engine:
        class: '%twig_engine.class%'
        tags:
            -
                name: twig.engine
                versions: 'Twig-0.9.10 / Twig-0.9.9 / Twig-0.9.8 / Twig-0.9.7 / Twig-0.9.6 / Twig-0.9.5 / Twig-0.9.4 / Twig-0.9.2 / Twig-0.9.1 / Twig-0.9.0'
                label: 'Twig 0.x'
