security:
    providers:
        oauth_provider:
             id: app.oauth_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            oauth:
                resource_owners:
                    google: "/login/check-google"
                    facebook: "/login/check-facebook"
                    twitter: "/login/check-twitter"
                    sensio_connect: "/login/check-sensio-connect"
                    github: "/login/check-github"
                login_path: /login
                failure_path: /login
                default_target_path: /welcome
                oauth_user_provider:
                    service: app.oauth_user_provider
        default:
            anonymous: ~

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https, host: 'twigfiddle\.com$' }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http, host: '127.0.0.1' }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, role: ROLE_USER }
        - { path: ^/logout, role: ROLE_USER }

hwi_oauth:
    firewall_names: ["main"]
    connect:
        confirmation: false
    resource_owners:
        google:
            type: google
            csrf: true
            client_id: %google_client_id%
            client_secret: %google_secret%
            scope: "profile"
            options:
                display: page
                access_type: online
                approval_prompt: auto
                login_hint: email address
        facebook:
            type: facebook
            csrf: true
            client_id: %facebook_client_id%
            client_secret: %facebook_secret%
            scope: "public_profile"
            options:
                display: page
        twitter:
            type: twitter
            csrf: true
            client_id: %twitter_client_id%
            client_secret: %twitter_secret%
            scope: ""
        sensio_connect:
            type: sensio_connect
            csrf: true
            client_id: %sensio_client_id%
            client_secret: %sensio_secret%
            scope: "SCOPE_PUBLIC"
        github:
            type: github
            csrf: true
            client_id: %github_client_id%
            client_secret: %github_secret%
            scope: ""
